repos:
  - repo: https://github.com/psf/black
    rev: "24.4.0"
    hooks:
      - id: black
        args: ["--line-length=120"]
        language_version: python3.12

  - repo: https://github.com/PyCQA/flake8
    rev: "7.0.0"
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]
        exclude: "__init__.py"

  - repo: local
    hooks:
      - id: run-script-pytest
        name: pytest
        entry: ./.pre-commit-script-pytest.sh
        language: script
        types: [python]
        pass_filenames: false
