services:
  api:
    image: python:3
    ports:
      - 5000:5000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - FLASK_APP=run
      - FLASK_ENV=production
    command: sh -c "pip install --no-cache-dir -r requirements.txt && flask run"
