"""init

Revision ID: 984cc73a3f80
Revises: 
Create Date: 2024-04-22 22:18:31.625173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984cc73a3f80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('algorithms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('userId', sa.String(length=32), nullable=False),
    sa.Column('isWorking', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_algorithms_userId'), 'algorithms', ['userId'], unique=False)
    op.create_table('mazes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('Easy', 'Medium', 'Hard', name='difficulty'), nullable=False),
    sa.Column('imgLink', sa.Text(), nullable=False),
    sa.Column('structure', sa.Text(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('isTest', sa.Boolean(), nullable=True),
    sa.Column('creator', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_mazes_creator'), 'mazes', ['creator'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('userId', sa.String(length=32), nullable=False),
    sa.Column('expiryDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_sessions_userId'), 'sessions', ['userId'], unique=True)
    op.create_table('user_followers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('userId', sa.String(length=32), nullable=False),
    sa.Column('followerId', sa.String(length=32), nullable=False),
    sa.CheckConstraint('userId!=followerId', name='_user_follower_check_'),
    sa.ForeignKeyConstraint(['followerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('userId', 'followerId', name='_user_follower_uc')
    )
    op.create_index(op.f('ix_user_followers_followerId'), 'user_followers', ['followerId'], unique=False)
    op.create_index(op.f('ix_user_followers_userId'), 'user_followers', ['userId'], unique=False)
    op.create_table('highscores',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('userId', sa.String(length=32), nullable=False),
    sa.Column('mazeId', sa.String(length=32), nullable=False),
    sa.Column('algorithm_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['algorithm_id'], ['algorithms.id'], ),
    sa.ForeignKeyConstraint(['mazeId'], ['mazes.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_highscores_algorithm_id'), 'highscores', ['algorithm_id'], unique=False)
    op.create_index(op.f('ix_highscores_mazeId'), 'highscores', ['mazeId'], unique=False)
    op.create_index(op.f('ix_highscores_userId'), 'highscores', ['userId'], unique=False)
    op.create_table('maze_followers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('mazeId', sa.String(length=32), nullable=False),
    sa.Column('followerId', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['followerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mazeId'], ['mazes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('mazeId', 'followerId', name='_maze_follower_uc')
    )
    op.create_index(op.f('ix_maze_followers_followerId'), 'maze_followers', ['followerId'], unique=False)
    op.create_index(op.f('ix_maze_followers_mazeId'), 'maze_followers', ['mazeId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maze_followers_mazeId'), table_name='maze_followers')
    op.drop_index(op.f('ix_maze_followers_followerId'), table_name='maze_followers')
    op.drop_table('maze_followers')
    op.drop_index(op.f('ix_highscores_userId'), table_name='highscores')
    op.drop_index(op.f('ix_highscores_mazeId'), table_name='highscores')
    op.drop_index(op.f('ix_highscores_algorithm_id'), table_name='highscores')
    op.drop_table('highscores')
    op.drop_index(op.f('ix_user_followers_userId'), table_name='user_followers')
    op.drop_index(op.f('ix_user_followers_followerId'), table_name='user_followers')
    op.drop_table('user_followers')
    op.drop_index(op.f('ix_sessions_userId'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_mazes_creator'), table_name='mazes')
    op.drop_table('mazes')
    op.drop_index(op.f('ix_algorithms_userId'), table_name='algorithms')
    op.drop_table('algorithms')
    op.drop_table('users')
    # ### end Alembic commands ###
