"""add isWorking flag

Revision ID: a3dfa5ea0bda
Revises: 186b1d182e84
Create Date: 2023-10-10 18:35:36.366154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3dfa5ea0bda'
down_revision = '186b1d182e84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('algorithms', sa.Column('isWorking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('algorithms', 'isWorking')
    # ### end Alembic commands ###
