"""delete foreign key of creator

Revision ID: ae7b9ca2d083
Revises: da6f4a0924f1
Create Date: 2023-11-06 20:58:10.357959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae7b9ca2d083'
down_revision = 'da6f4a0924f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('mazes_creator_fkey', 'mazes', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('mazes_creator_fkey', 'mazes', 'users', ['creator'], ['id'])
    # ### end Alembic commands ###
