"""2/2 add back creator with new type and foreign key

Revision ID: da6f4a0924f1
Revises: daaeb01fddbc
Create Date: 2023-11-06 20:52:10.667130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da6f4a0924f1'
down_revision = 'daaeb01fddbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mazes', sa.Column('creator', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'mazes', 'users', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mazes', type_='foreignkey')
    op.drop_column('mazes', 'creator')
    # ### end Alembic commands ###
