"""1/2 remove creator

Revision ID: daaeb01fddbc
Revises: f48e886d51d3
Create Date: 2023-11-06 20:51:28.110017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daaeb01fddbc'
down_revision = 'f48e886d51d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mazes', 'creator')
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.add_column('mazes', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
