"""change name for user table to users

Revision ID: f48e886d51d3
Revises: c35b303a2927
Create Date: 2023-11-06 18:45:02.289339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48e886d51d3'
down_revision = 'c35b303a2927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.String(length=32), nullable=False),
                    sa.Column('username', sa.String(length=32), nullable=True),
                    sa.Column('email', sa.String(length=32), nullable=True),
                    sa.Column('password', sa.Text(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.drop_constraint('algorithms_userId_fkey',
                       'algorithms', type_='foreignkey')
    op.create_foreign_key(None, 'algorithms', 'users', ['userId'], ['id'])
    op.drop_constraint('highscores_userId_fkey',
                       'highscores', type_='foreignkey')
    op.create_foreign_key(None, 'highscores', 'users', ['userId'], ['id'])
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'highscores', type_='foreignkey')
    op.create_foreign_key('highscores_userId_fkey',
                          'highscores', 'user', ['userId'], ['id'])
    op.drop_constraint(None, 'algorithms', type_='foreignkey')
    op.create_foreign_key('algorithms_userId_fkey',
                          'algorithms', 'user', ['userId'], ['id'])
    op.create_table('user',
                    sa.Column('id', sa.VARCHAR(length=32),
                              autoincrement=False, nullable=False),
                    sa.Column('email', sa.VARCHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.Column('password', sa.TEXT(),
                              autoincrement=False, nullable=False),
                    sa.Column('username', sa.VARCHAR(length=32),
                              autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='user_pkey'),
                    sa.UniqueConstraint('email', name='user_email_key'),
                    sa.UniqueConstraint('id', name='user_id_key'),
                    sa.UniqueConstraint('username', name='user_username_key')
                    )
    op.drop_table('users')
    # ### end Alembic commands ###
